CREATE TABLE BRANDS (
	ID          SERIAL      PRIMARY KEY,
    RETAILER_ID UUID        NOT NULL,
    BRAND       VARCHAR(50) NOT NULL CHECK (BRAND ~ '\S')
);

CREATE TABLE CATEGORIES (
	ID       SERIAL      PRIMARY KEY,
    CATEGORY VARCHAR(50) NOT NULL UNIQUE CHECK (CATEGORY ~ '\S')
);

CREATE TABLE PRODUCT_STATUS (
	ID     SERIAL      PRIMARY KEY,
	STATUS VARCHAR(50) NOT NULL UNIQUE CHECK (STATUS ~ '\S')
);

CREATE TABLE PRODUCTS (
	ID          UUID           PRIMARY KEY,
	RETAILER_ID UUID           NOT NULL,
	SKU         VARCHAR(30)    NOT NULL,
	NAME        VARCHAR(100)   NOT NULL CHECK (NAME ~ '\S'),
	DESCRIPTION VARCHAR(250)   NOT NULL CHECK (DESCRIPTION ~ '\S'),
	PRICE       NUMERIC(12, 2) NOT NULL CHECK (PRICE >= 0),
	INVENTORY   INT            NOT NULL CHECK (INVENTORY >= 0),
	STATUS_ID   INT            REFERENCES PRODUCT_STATUS(ID),
	BRAND_ID    INT            REFERENCES BRANDS(ID),
	CREATED_AT  TIMESTAMP      NOT NULL,
	UPDATED_AT  TIMESTAMP      NOT NULL CHECK (UPDATED_AT >= CREATED_AT),
	CONSTRAINT UNIQUE_RETAILER_PRODUCT_SKU UNIQUE (ID, RETAILER_ID)
);

CREATE TABLE PRODUCT_CATEGORY (
	PRODUCT_ID  UUID        REFERENCES PRODUCTS(ID),
	CATEGORY_ID INT         REFERENCES CATEGORIES(ID)
);

